# Generated by Django 5.2.6 on 2026-08-26 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_gameconfig_racha_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='hide_racha_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='players_per_team',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='vote_day',
            field=models.CharField(choices=[('dom', 'Domingo'), ('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado')], default='ter', max_length=3),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='vote_end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='vote_start_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
    ]
